import { test } from "@playwright/test";
import fs from "node:fs/promises";
import path from "node:path";

// Auto-generates docs/WIDGETS.md + docs/widgets/*.png as a "living" gallery.
// Runs as part of `yarn test:e2e`. To skip during fast iteration use
// `yarn test:e2e --grep-invert @docs`.
//
// Screenshots are not pixel-diffed — the intent is a living reference, not
// visual regression testing. Time/weather/news content varies per run and
// that's expected. Diff noise in git is the trade-off for always-current
// documentation.

interface WidgetDoc {
  key: string;
  displayName: string;
  controls: string[];
  notes?: string;
}

const WIDGETS: WidgetDoc[] = [
  {
    key: "time",
    displayName: "Time",
    controls: ["24-hour", "Show seconds", "Show date", "Date format"],
    notes: "Fluid pixel sizing scales with container width.",
  },
  {
    key: "weather",
    displayName: "Weather",
    controls: ["City", "Metric rotation (seconds)"],
    notes:
      "Requires `VITE_OPEN_WEATHER_API_KEY` in `.env`. Renders 12-hour clock face with weather condition icons around the perimeter.",
  },
  {
    key: "news",
    displayName: "News",
    controls: ["Article limit"],
    notes: "Fetches RSS-aggregated headlines from the Panda API.",
  },
  {
    key: "text",
    displayName: "Text",
    controls: ["Content"],
    notes: "Minimal placeholder for arbitrary text.",
  },
];

const VIEWPORTS = [
  { label: "wide", width: 1280, height: 720 },
  { label: "narrow", width: 520, height: 400 },
];

const OUT_DIR = path.resolve("docs/widgets");
const DOC_PATH = path.resolve("docs/WIDGETS.md");

test.describe.serial("@docs widget gallery", () => {
  test.beforeAll(async () => {
    await fs.mkdir(OUT_DIR, { recursive: true });
  });

  for (const w of WIDGETS) {
    for (const vp of VIEWPORTS) {
      test(`@docs ${w.key} @ ${vp.label}`, async ({ page }) => {
        await page.setViewportSize({ width: vp.width, height: vp.height });
        await page.goto(`/?widget=${w.key}`, { waitUntil: "networkidle" });
        // Buffer for post-network paints (widget timers, ResizeObserver, etc).
        await page.waitForTimeout(1200);
        await page.screenshot({
          path: path.join(OUT_DIR, `${w.key}-${vp.label}.png`),
          animations: "disabled",
        });
      });
    }
  }

  test(`@docs catalog overview`, async ({ page }) => {
    await page.setViewportSize({ width: 1440, height: 900 });
    await page.goto("/catalog", { waitUntil: "networkidle" });
    await page.waitForTimeout(1500);
    await page.screenshot({
      path: path.join(OUT_DIR, "catalog.png"),
      fullPage: true,
      animations: "disabled",
    });
  });

  test.afterAll(async () => {
    const lines: string[] = [
      "# Widget Gallery",
      "",
      "> Auto-generated by `tests/e2e/docs.spec.ts` — regenerated on every `yarn test:e2e`.",
      "> Screenshots are captured in isolation via `?widget=<key>`.",
      "",
      "| widget | controls |",
      "|---|---|",
      ...WIDGETS.map(
        (w) =>
          `| \`${w.key}\` | ${w.controls.map((c) => `\`${c}\``).join(", ")} |`,
      ),
      "",
      "## Catalog Overview",
      "",
      "All widgets on the `/catalog` page:",
      "",
      "![Catalog overview](./widgets/catalog.png)",
      "",
    ];

    for (const w of WIDGETS) {
      lines.push(`## ${w.displayName}`);
      lines.push("");
      if (w.notes) {
        lines.push(w.notes);
        lines.push("");
      }
      for (const vp of VIEWPORTS) {
        lines.push(`**${vp.label}** — ${vp.width}×${vp.height}`);
        lines.push("");
        lines.push(
          `![${w.displayName} — ${vp.label}](./widgets/${w.key}-${vp.label}.png)`,
        );
        lines.push("");
      }
    }

    await fs.writeFile(DOC_PATH, lines.join("\n"), "utf8");
  });
});
