import type { Metadata } from "next";
import { Inter } from "next/font/google";
import React from "react";
// import "react-grid-layout/css/styles.css";
import "react-resizable/css/styles.css";
import "./globals.css";
import "./react-grid.scss";
// import "./glo"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Hakboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}

